name: Monitor Inactive Open Issues

on:
  schedule:
    - cron: "* * * * 1-5"

jobs:
  inactive-labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - uses: neonidian/teams-notify-build-status@v3
        with:
                  webhookUrl: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
      
      - name: Check for inactive open issues
        uses: actions/github-script@v6
        
        env:
                  
          script: |
            // - github: A pre-authenticated octokit/rest.js client
            const { owner, repo } = context.repo;
            const openLabel = "Status: Open";
            const parsedDays = 14;
            const timeThreshold = parsedDays * 24 * 60 * 60 * 1000;
            
            // Query all GH issues that are open
            const issuesResponse = await github.rest.issues.listForRepo({
              owner,
              repo,
              labels: openLabel,
              state: "open",  
            });
            for (const issue of issuesResponse.data) {
              const updatedAt = new Date(issue.updated_at).getTime();
              const currentTime = new Date().getTime();
              const updateMessage = `Please update the issue #${issue.number}.`;
              
        message: Workflow run passed !!
            }
