name: Reusable Teams Integration

on:
  workflow_call:
    inputs:
     issue:
       required: false
       type: string


jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: neonidian/teams-notify-build-status@v3
      with:
        webhookUrl: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
        message: Please update the issue ${{ inputs.issue }}
        
